package datastore

import (
	"context"
	"log"
	"os"

	"github.com/SimplQ/simplQ-golang/internal/models"

	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"
)

// A Structure with Collections frequently used and a pointer to the client
type MongoDB struct {
	Client *mongo.Client
	Queue  *mongo.Collection
	Token  *mongo.Collection
}

func NewMongoDB() *MongoDB {
	// Use local development mongodb instance if env variable not set
	uri := "mongodb://root:example@localhost:27017/?maxPoolSize=20&w=majority"

	if val, ok := os.LookupEnv("MONGO_URI"); ok {
		uri = val
	}

	log.Println("Connecting to MongoDB...")

	client, err := mongo.Connect(context.TODO(), options.Client().ApplyURI(uri))

	if err != nil {
		log.Fatal(err)
	}

	new_mongodb := MongoDB{
		client,
		client.Database("simplq").Collection("queue"),
		client.Database("simplq").Collection("token"),
	}

	log.Println("Successfully connected to MongoDB!")

	return &new_mongodb
}

func (mongodb MongoDB) CreateQueue(queue models.Queue) (models.QueueId, error) {
	// Set id to empty so its generated by mongoDB
	queue.Id = ""

	result, err := mongodb.Queue.InsertOne(context.TODO(), queue)

	if err != nil {
		return queue.Id, err
	}

	stringId := result.InsertedID.(primitive.ObjectID).Hex()

	return models.QueueId(stringId), nil
}

func (mongodb MongoDB) ReadQueue(id models.QueueId) (models.Queue, error) {
	result := models.Queue{}

	// convert id string to ObjectId
	queueId, _ := primitive.ObjectIDFromHex(string(id))

	err := mongodb.Queue.FindOne(context.TODO(), bson.M{"_id": queueId}).Decode(&result)

	if err != nil {
		return result, err
	}

	return result, nil
}

func (mongodb MongoDB) SetIsPaused(id models.QueueId, isPaused bool) (*mongo.UpdateResult, error) {
	queueId, _ := primitive.ObjectIDFromHex(string(id))
	result, err := mongodb.Queue.UpdateOne(
		context.TODO(),
		bson.M{"_id": queueId},
		bson.D{
			{"$set", bson.D{{"isPaused", isPaused}}},
		},
	)

	if err != nil {
		return result, err
	}

	return result, nil
}

func (mongodb MongoDB) DeleteQueue(id models.QueueId) (*mongo.DeleteResult, error) {
	queueId, _ := primitive.ObjectIDFromHex(string(id))
	result, err := mongodb.Queue.DeleteOne(
		context.TODO(),
		bson.M{"_id": queueId})
	if err != nil {
		return result, err
	}

	return result, nil
}

func (mongodb MongoDB) AddTokenToQueue(models.QueueId, models.Token) {
	panic("Not implemented")
}

func (mongodb MongoDB) ReadToken(models.TokenId) {
	panic("Not implemented")
}

func (mongodb MongoDB) RemoveToken(models.TokenId) {
	panic("Not implemented")
}
