name: Post-push-checks

on: [push, pull_request]
      
jobs:
  build-check:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Verify dependencies
        run: go mod verify

      # ... acts as a wildcard: https://stackoverflow.com/a/13321739/10281310
      - name: Build
        run: go build -v ./...

  run-vet:
    name: Vet
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Run go vet
        run: go vet ./...

  run-gofmt:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Run gofmt
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          # Enable linters
          gofmt: true
          gofmt_dir: ./
          auto_fix: true